Keys = {
    ['ESC'] = 322, ['F1'] = 288, ['F2'] = 289, ['F3'] = 170, ['F5'] = 166, ['F6'] = 167, ['F7'] = 168, ['F8'] = 169, ['F9'] = 56, ['F10'] = 57,
    ['~'] = 243, ['1'] = 157, ['2'] = 158, ['3'] = 160, ['4'] = 164, ['5'] = 165, ['6'] = 159, ['7'] = 161, ['8'] = 162, ['9'] = 163, ['-'] = 84, ['='] = 83, ['BACKSPACE'] = 177,
    ['TAB'] = 37, ['Q'] = 44, ['W'] = 32, ['E'] = 38, ['R'] = 45, ['T'] = 245, ['Y'] = 246, ['U'] = 303, ['P'] = 199, ['['] = 39, [']'] = 40, ['ENTER'] = 18,
    ['CAPS'] = 137, ['A'] = 34, ['S'] = 8, ['D'] = 9, ['F'] = 23, ['G'] = 47, ['H'] = 74, ['K'] = 311, ['L'] = 182,
    ['LEFTSHIFT'] = 21, ['Z'] = 20, ['X'] = 73, ['C'] = 26, ['V'] = 0, ['B'] = 29, ['N'] = 249, ['M'] = 244, [','] = 82, ['.'] = 81,
    ['LEFTCTRL'] = 36, ['LEFTALT'] = 19, ['SPACE'] = 22, ['RIGHTCTRL'] = 70,
    ['HOME'] = 213, ['PAGEUP'] = 10, ['PAGEDOWN'] = 11, ['DELETE'] = 178,
    ['LEFT'] = 174, ['RIGHT'] = 175, ['TOP'] = 27, ['DOWN'] = 173,
}

Config = Config or {}

Config.RepeatTimeout = 2000
Config.CallRepeats = 10
Config.OpenPhone = 244
Config.PhoneApplications = {
    ["phone"] = {
        app = "phone",
        color = "#04b543",
        icon = "fa fa-phone-alt",
        tooltipText = "",
        tooltipPos = "top",
        job = false,
        blockedjobs = {},
        slot = 1,
        Alerts = 0,
    },
    ["Messages"] = {
        app = "whatsapp",
        color = "#069de1",
        icon = "fas fa-comment-dots",
        tooltipText = "",
        tooltipPos = "top",
        style = "font-size: 2.8vh";
        job = false,
        blockedjobs = {},
        slot = 2,
        Alerts = 0,
    },
    ["mail"] = {
        app = "mail",
        color = "#ff002f",
        icon = "fas fa-envelope",
        tooltipText = "",
        job = false,
        blockedjobs = {},
        slot = 3,
        Alerts = 0,
    },
    ["settings"] = {
        app = "settings",
        color = "#636e72",
        icon = "fa fa-cog",
        tooltipText = "",
        tooltipPos = "top",
        style = "padding-right: .08vh; font-size: 2.3vh";
        job = false,
        blockedjobs = {},
        slot = 4,
        Alerts = 0,
    },
    ["garage"] = {
        app = "garage",
        color = "#575fcf",
        icon = "fas fa-warehouse",
        tooltipText = "Vehicles",
        job = false,
        blockedjobs = {},
        slot = 5,
        Alerts = 0,
    },
    ["twitter"] = {
        app = "twitter",
        color = "#1da1f2",
        icon = "fab fa-twitter",
        tooltipText = "Twitter",
        tooltipPos = "top",
        job = false,
        blockedjobs = {},
        slot = 6,
        Alerts = 0,
    },
    ["advert"] = {
        app = "advert",
        color = "#ff8f1a",
        icon = "fas fa-ad",
        tooltipText = "Adverts",
        job = false,
        blockedjobs = {},
        slot = 7,
        Alerts = 0,
    },
    ["bank"] = {
        app = "bank",
        color = "#9c88ff",
        icon = "fas fa-university",
        tooltipText = "Bank",
        job = false,
        blockedjobs = {},
        slot = 8,
        Alerts = 0,
    },
    --[[["crypto"] = {
        app = "crypto",
        color = "#004682",
        icon = "fas fa-chart-pie",
        tooltipText = "Crypto",
        job = false,
        blockedjobs = {},
        slot = 9,
        Alerts = 0,
    },--]]
    ["lawyers"] = {
        app = "lawyers",
        color = "#353b48",
        icon = "fas fa-user-tie",
        tooltipText = "Lawyers",
        tooltipPos = "right",
        job = false,
        blockedjobs = {},
        slot = 9,
        Alerts = 0,
    },
    -- ["racing"] = {
    --     app = "racing",
    --     color = "#353b48",
    --     icon = "fas fa-flag-checkered",
    --     tooltipText = "Racing",
    --     job = false,
    --     blockedjobs = {
    --         "police"
    --     },
    --     slot = 10,
    --     Alerts = 0,
    -- },
    ["realestate"] = {
        app = "realestate",
        color = "#00b300",
        icon = "fas fa-sign",
        tooltipText = "Real Estate",
        tooltipPos = "right",
        job = false,
        blockedjobs = {},
        slot = 10,
        Alerts = 0,
    },
    ["skills"] = {
        app = "skills",
        color = "#5c2695",
        icon = "fas fa-heartbeat",
        tooltipText = "Lucid Fit",
        tooltipPos = "right",
        job = false,
        blockedjobs = {},
        slot = 11,
        Alerts = 0,
    },
    ["anonChat"] = {
        app = "anonChat",
        color = "#2d132c",
        icon = "fas fa-user-secret",
        tooltipText = "Dark Chat",
        tooltipPos = "right",
        job = false,
        blockedjobs = {'police'},
        slot = 12,
        Alerts = 0,
    },
    ["airLines"] = {
        app = "airLines",
        color = "#e6ba40;",
        icon = "fas fa-plane-departure",
        tooltipText = "Lucid Airlines",
        tooltipPos = "right",
        job = false,
        blockedjobs = {},
        slot = 13,
        Alerts = 0,
    },
    ["twitch"] = {
        app = "twitch",
        color = "#6441a5;",
        icon = "fas fa-tv",
        tooltipText = "LC Live",
        tooltipPos = "right",
        job = false,
        blockedjobs = {},
        slot = 14,
        Alerts = 0,
    },
    ["radio"] = {
        app = "radio",
        color = "#c3aae0;",
        icon = "fas fa-broadcast-tower",
        tooltipText = "LC radio",
        tooltipPos = "right",
        job = false,
        blockedjobs = {},
        slot = 15,
        Alerts = 0,
    },
    ["taxi"] = {
        app = "taxi",
        color = "#ccb806;",
        icon = "fas fa-taxi",
        tooltipText = "Taxi",
        tooltipPos = "right",
        job = false,
        blockedjobs = {},
        slot = 16,
        Alerts = 0,
    },
    --     ["houses"] = {
    --     app = "houses",
    --     color = "#27ae60",
    --     icon = "fas fa-home",
    --     tooltipText = "Houses",
    --     job = false,
    --     blockedjobs = {},
    --     slot = 11,
    --     Alerts = 0,
    -- },
    --[["9GAG"] = {
        app = "9gag",
        color = "#353b48",
        icon = "fas fa-meteor",
        tooltipText = "9gag",
        job = false,
        blockedjobs = {},
        slot = 11,
        Alerts = 0,
    },--]]
}