var questionList = [
      // QUESTION 1
    {   question : "How many feet must you signal before making a turn?:",
        propositionA : "50",
        propositionB : "100",
        propositionC : "150",
        propositionD : "200",
        reponse : "B"},
      // QUESTION 2
    {   question : "The light changes from green to yellow as you approach an intersection. You should:",
        propositionA : "Slow to stop",
        propositionB : "Speed up and clear the intersection",
        propositionC : "Check if there is any cops around, and if not then keep on driving",
        propositionD : "Keep on driving",
        reponse : "A"},
     // QUESTION 3
    {   question : "When you hear a siren or see an emergency vehicle, you shoud:",
        propositionA : "Slow down and let it pass by",
        propositionB : "Pull over and stop",
        propositionC : "Keep on driving",
        propositionD : "Drive away",
        reponse : "B"},
      // QUESTION 4
  {   question : "Before every lane change you must:",
        propositionA : "Check your mirrors",
        propositionB : "Check your blind spots",
        propositionC : "Signal your intentions",
        propositionD : "All of the above",
        reponse : "D"},
      // QUESTION 5
  {   question : "What blood alcohol level is classified as driving while intoxicated?",
        propositionA : "0.05%",
        propositionB : "0.18%",
        propositionC : "0.08%",
        propositionD : "0.06%",
        reponse : "C"},
      // QUESTION 6
  {   question : "Which of the following are signs of road rage?",
        propositionA : "Forcing a car off the road",
        propositionB : "Blowing the horn excessively",
        propositionC : "Tailgating",
        propositionD : "All of the above",
        reponse : "D"},
      // QUESTION 7
  {   question : "A pedestrian has a do not cross signal, what do you do?",
        propositionA : "You let them pass",
        propositionB : "You observe before continuing",
        propositionC : "You wave to tell them to cross",
        propositionD : "You continue because your traffic light is green",
        reponse : "D"},
      // QUESTION 8
  {   question : "You must NOT pass:",
        propositionA : "A school bus with flashing red lights stopped ahead",
        propositionB : "If there is a solid yellow line next to your lane",
        propositionC : "If there is an upcoming hill or a curve where there is no clear visibility",
        propositionD : "In any of the above situations",
        reponse : "D"},
      // QUESTION 9
  {   question : "Without any prior indication, the speed limit in a residential area is: _ mph",
        propositionA : "30 mph",
        propositionB : "40 mph",
        propositionC : "50 mph",
        propositionD : "60 mph",
        reponse : "A"},
      // QUESTION 10
  {   question : "A person who drives much slower than the speed limit: ",
        propositionA : "Is a very safe driver",
        propositionB : "Always has the right-of-way",
        propositionC : "Should not let following cars pass",
        propositionD : "May create a dangerous driving environment",
        reponse : "D"},
      // QUESTION 11
        {   question : "If an officer is directing traffic at a working traffic light, drivers should:",
        propositionA : "Follow the directions indicated by the traffic light",
        propositionB : "Follow the directions given by the officer",
        propositionC : "Honk at the officer",
        propositionD : "Check to see what the cars next to them are doing",
        reponse : "B"},
      // QUESTION 12
      {   question : "The effect that lack of sleep has on your safe driving ability is the same as: ",
      propositionA : "The effect that alcohol has",
      propositionB : "The effect that amphetamines have",
      propositionC : "The effect that anger has",
      propositionD : "The effect that driving with teenagers has",
      reponse : "A"},
      // QUESTION 13
      {   question : "Highway markings:",
      propositionA : "Are usually not important",
      propositionB : "Are only found in construction zones",
      propositionC : "Provide information for drivers",
      propositionD : "Are usually red and blue in color",
      reponse : "C"},
]
